In [1]:
import pandas as pd
import os
from pathlib import Path
import Data
import coordinates

In [2]:
currpath = os.getcwd()
mypath = Path().absolute().parent # each '.parent' goes one level up - vary as required
#print(mypath)
#os.chdir(mypath)
os.chdir(os.path.dirname(os.path.abspath("meuse_data.csv")))
print(Path().absolute())

C:\Users\chloe\OneDrive\AY2023 & 2024 FYP\FYP-Code\FYP-Spatial-Analytics

In [2]:
df = pd.read_csv("Data/meuse_data.csv")
df2 = df
df2.describe()

,x,y,cadmium,copper,lead,zinc,elev,dist,om,ffreq,soil,lime,dist.m
count,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,153.000000,155.000000,155.000000,155.000000,155.000000
mean,180004.600000,331634.935484,3.245806,40.316129,153.361290,469.716129,8.165394,0.240017,7.478431,1.606452,1.451613,0.283871,290.322581
std,746.039775,1047.746801,3.523746,23.680436,111.320054,367.073788,1.058657,0.197702,3.432966,0.734111,0.636483,0.452336,226.799927
min,178605.000000,329714.000000,0.200000,14.000000,37.000000,113.000000,5.180000,0.000000,1.000000,1.000000,1.000000,0.000000,10.000000
25%,179371.000000,330762.000000,0.800000,23.000000,72.500000,198.000000,7.546000,0.075687,5.300000,1.000000,1.000000,0.000000,80.000000
50%,179991.000000,331633.000000,2.100000,31.000000,123.000000,326.000000,8.180000,0.211843,6.900000,1.000000,1.000000,0.000000,270.000000
75%,180629.500000,332463.000000,3.850000,49.500000,207.000000,674.500000,8.955000,0.364067,9.000000,2.000000,2.000000,1.000000,450.000000
max,181390.000000,333611.000000,18.100000,128.000000,654.000000,1839.000000,10.520000,0.880389,17.000000,3.000000,3.000000,1.000000,1000.000000

In [3]:
import geoplot as gplt
import geopandas as gpd
import geoplot.crs as gcrs
import imageio
import matplotlib.pyplot as plt
import mapclassify as mc
import numpy as np
import shapely

In [5]:
from shapely.geometry import Point

collision_points = df2.apply(
    lambda srs: Point(float(df2['x']), float(df2['y'])),
    axis='columns'
)
collision_points

TypeError: cannot convert the series to <class 'float'>